print('================= Start analysis ====================')
print('*** Read in activity and feature data ...')
activity_labels <- read.table('UCI HAR Dataset/activity_labels.txt', col.names = c('activity_id', 'activity'))
features <- read.table('UCI HAR Dataset/features.txt', stringsAsFactors = FALSE)
print('*** Read in test data ...')
x_test <- read.table('UCI HAR Dataset/test/X_test.txt')
y_test <- read.table('UCI HAR Dataset/test/Y_test.txt')
subject_test <- read.table('UCI HAR Dataset/test/subject_test.txt')
print('*** Read in training data ...')
x_train <- read.table('UCI HAR Dataset/train/X_train.txt')
y_train <- read.table('UCI HAR Dataset/train/Y_train.txt')
subject_train <- read.table('UCI HAR Dataset/train/subject_train.txt')

test <- cbind(subject_test, y_test, x_test)
train <- cbind(subject_train, y_train, x_train)
print('*** Merge test and training data ...')
data <- rbind(test, train)
names(data) <- c('subject', 'activity_id', features$V2)
filtered_features <- grep('mean|std', names(data), value = TRUE)
print('*** Extract only mean and standard deviation of each measurement ...')
filtered_data <- data[, which(names(data) %in% c('subject', 'activity_id', filtered_features))]
print('*** Set descriptive column names ...')
mrg <- merge(filtered_data, activity_labels, by = 'activity_id')
selected_cols <- c('subject', 'activity', filtered_features)
mrg <- mrg[, selected_cols]
print('*** Create tidy data ...')
tidy_data <- aggregate(mrg, by = list(mrg$subject, mrg$activity), FUN = mean)
tidy_data <- tidy_data[, -c(3:4)]
names(tidy_data)[1:2] <- c('subject', 'activity')
print('*** Output tidy data to tidy_data.txt ...')
write.table(tidy_data, 'tidy_data.txt', row.name = FALSE)
print('================= Done! ====================')